name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  workflow_run:
    workflows:
      - 'Checks'
      - 'Docker Image CI'

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: automerge
        name: Automerge Dependabot PR
        uses: "pascalgn/automerge-action@v0.16.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}